from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib import colors
import os
from datetime import datetime


def create_pdf_report(
    score,
    suggestions,
    resume_name
):

    if not os.path.exists("reports"):
        os.makedirs("reports")

    pdf_path = "reports/resume_report.pdf"

    c = canvas.Canvas(
        pdf_path,
        pagesize=letter
    )

    width, height = letter

    # Background Header
    c.setFillColor(colors.darkblue)
    c.rect(0, 730, width, 80, fill=1)

    # Title
    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 28)

    c.drawString(
        140,
        760,
        "SmartHire AI Report"
    )

    # Main Text
    c.setFillColor(colors.black)

    # Date
    c.setFont("Helvetica", 12)

    c.drawString(
        50,
        690,
        f"Generated On: {datetime.now().strftime('%d-%m-%Y %H:%M')}"
    )

    # Resume Name
    c.drawString(
        50,
        665,
        f"Resume File: {resume_name}"
    )

    # ATS Score
    c.setFont("Helvetica-Bold", 22)

    if score >= 75:
        c.setFillColor(colors.green)

    elif score >= 50:
        c.setFillColor(colors.orange)

    else:
        c.setFillColor(colors.red)

    c.drawString(
        50,
        610,
        f"ATS Score: {score}%"
    )

    # Strength
    c.setFillColor(colors.black)

    c.setFont("Helvetica-Bold", 18)

    strength = ""

    if score >= 75:
        strength = "Excellent Resume"

    elif score >= 50:
        strength = "Good Resume"

    else:
        strength = "Needs Improvement"

    c.drawString(
        50,
        575,
        f"Resume Strength: {strength}"
    )

    # Suggestions
    c.setFont("Helvetica-Bold", 18)

    c.drawString(
        50,
        520,
        "Suggestions:"
    )

    c.setFont("Helvetica", 14)

    y = 490

    for suggestion in suggestions:

        c.drawString(
            70,
            y,
            f"- {suggestion}"
        )

        y -= 28

    # Footer
    c.setFont("Helvetica-Oblique", 12)

    c.setFillColor(colors.grey)

    c.drawString(
        50,
        70,
        "Generated by SmartHire AI"
    )

    c.save()

    return pdf_path